#!/usr/bin/env bash

# Prints a Slurm cluster status with 1 line per node/partition and job info
# Author: Ole.H.Nielsen@fysik.dtu.dk
# Homepage: https://github.com/OleHolmNielsen/Slurm_tools/
my_version="pestat Github version"

#####################################################################################
#
# Environment configuration lines
#

# CONFIGURE the paths of commands:
# Directory where Slurm commands live:
export prefix=/usr/bin
# The awk command
my_awk=$prefix/awk
# Job grace time (seconds) before we may flag the node
export jobgracetime=900
# Global configuration file for pestat
export PESTAT_GLOBAL_CONFIG=/etc/pestat.conf
# Per-user configuration file for pestat
export PESTAT_CONFIG=$HOME/.pestat.conf
# Omit nodes with these states (list separated by spaces):
export statedown="down down~ idle~ alloc# drain drng resv maint boot"
# End of CONFIGURE lines

#####################################################################################
#
# Command usage:
#
function usage()
{
	cat <<EOF
Usage: pestat [-p partition(s)] [-P] [-u username] [-g groupname] [-A accountname] [-a]
	[-q qoslist] [-s/-t statelist] [-n/-w hostlist] [-j joblist] [-G] [-N]
	[-f | -F | -m free_mem | -M free_mem ] [-1|-2] [-d] [-S] [-E] [-T] [-C|-c] [-V] [-h]
where:
	-p partition: Select only partion <partition>
        -P: Include all partitions, including hidden and unavailable ones
	-u username: Print only jobs of a single user <username> 
	-g groupname: Print only users in UNIX group <groupname>
	-A accountname: Print only jobs in Slurm account <accountname>
	-a: Print User(Account) information after each JobID
	-q qoslist: Print only QOS in the qoslist <qoslist>
	-R reservationlist: Print only node reservations <reservationlist>
	-s|-t statelist: Print only nodes with state in <statelist> 
	-n|-w hostlist: Print only nodes in hostlist
	-j joblist: Print only nodes in job <joblist>
	-G: Print GRES (Generic Resources) in addition to JobID
	-N: Print JobName in addition to JobID
	-f: Print only nodes that are flagged by * (unexpected load etc.)
	-F: Like -f, but only nodes flagged in RED are printed.
	-m free_mem: Print only nodes with free memory LESS than free_mem MB
	-M free_mem: Print only nodes with free memory GREATER than free_mem MB (under-utilized)
	-d: Omit nodes with states: $statedown
	-1: Default: Only 1 line per node (unique nodes in multiple partitions are printed once only)
	-2: 2..N lines per node which participates in multiple partitions 
	-S: Job StartTime is printed after each JobID/user
	-E: Job EndTime is printed after each JobID/user
	-T: Job TimeUsed is printed after each JobID/user
	-C: Color output is forced ON
	-c: Color output is forced OFF
	-h: Print this help information
	-V: Version information

Global configuration file for pestat: $PESTAT_GLOBAL_CONFIG
Per-user configuration file for pestat: $PESTAT_CONFIG
EOF
}

#####################################################################################
#
# Configuration of default pestat parameters.
# Default values are overridden by $PESTAT_GLOBAL_CONFIG and $PESTAT_CONFIG
#

# Flagging nodes
export flaglevel=-1
# Free memory threshold value (off by default)
export free_mem_less=-1
export free_mem_more=-1

# Thresholds for flagging nodes
export cpuload_delta1=4.0	# CPU load delta from ideal load (RED)
export cpuload_delta2=2.0	# CPU load delta from ideal load (MAGENTA)
export memory_thres1=0.1	# Fraction of memory which is free (RED)
export memory_thres2=0.2	# Fraction of memory which is free (MAGENTA)

# Colored output by default:
export colors=1

# Print all nodes by default
export printallnodes=1
# Unique nodes only (nodes in multiple partitions are printed once only)
# export uniquenodes=0
# We have changed uniquenodes=1 to be the default now
export uniquenodes=1

# Omit nodes with states: $statedown
export omitdown=0

# Controls whether GRES (Generic Resources) will be printed
export printgres=0
# Controls whether User(Account) will be printed after each JobID
export printaccount=0
# Controls whether JobName will be printed
export printjobname=0
# Controls whether job StartTime and EndTime will be printed
export printjobstarttime=0
export printjobendtime=0

# Select UNIX group
export groupname=""

export partition=""
# By default sinfo does not show hidden and unavailable partitions
export all_partitions=""
export hostlist=""

# Remove any custom format for squeue and Slurm time format (may mess up output formatting)
export SQUEUE_FORMAT=""
export SLURM_TIME_FORMAT=""

# Check if output is NOT a terminal: Turn colors off (can be overruled by "-C" flag).
FD=1	# File Descriptor no. 1 = stdout
if test ! -t $FD
then
	export colors=0
fi

# First read the global configuration file for pestat
if test -s $PESTAT_GLOBAL_CONFIG
then
	source $PESTAT_GLOBAL_CONFIG
fi

# Next read the per-user configuration file for pestat
if test -s $PESTAT_CONFIG
then
	source $PESTAT_CONFIG
fi

# Serialize an optional per-node GPU descriptor map for the awk script.
# Set PESTAT_GPU_MODEL as a Bash associative array in a config file, mapping
# each node to an "arch/model/vram" string, e.g. [comp-gpu14]="Ampere/A5000/24G".
# This lets sites show the real GPU (arch, product, memory) per node, since Slurm
# often reports only a coarse type (e.g. Ampere, covering both A4000 and A5000)
# or none at all. Serialized format passed to awk: node=descriptor|node=descriptor|...
gpumodelmap=""
if declare -p PESTAT_GPU_MODEL >/dev/null 2>&1
then
	for _node in "${!PESTAT_GPU_MODEL[@]}"
	do
		gpumodelmap="${gpumodelmap}${_node}=${PESTAT_GPU_MODEL[$_node]}|"
	done
fi
export gpumodelmap

# Largest GPU count on any selected node, used to align the GPU availability bar
# column (the per-GPU [....] schema shown by -G).
maxgpus=$($prefix/sinfo -h -N $all_partitions $partition $hostlist $statelist -O "Gres:60" 2>/dev/null \
	| awk '{ if (match($0,/gpu:([^:]+:)?[0-9]+/)) { s=substr($0,RSTART,RLENGTH); sub(/.*:/,"",s); if (s+0>m) m=s+0 } } END{ print m+0 }')
export maxgpus

# Per-node "cores:mem(MB):gpus" map, used to color each job GPU request by how its
# CPU-per-GPU / mem-per-GPU compares to the node fair share (total_cpu/total_gpu etc.).
noderatiomap=$($prefix/sinfo -h -N $all_partitions $partition $hostlist $statelist -O "NodeList:50,CPUs:20,Memory:20,Gres:60" 2>/dev/null \
	| awk '{ g=0; if (match($4,/gpu:([^:]+:)?[0-9]+/)) { s=substr($4,RSTART,RLENGTH); sub(/.*:/,"",s); g=s+0 }
		 if (g>0) printf "%s=%s:%s:%d|", $1, $2, $3, g }')
export noderatiomap

#####################################################################################
#
# Parse command options
#

while getopts "p:Pu:g:A:q:s:t:n:j:w:m:M:R:aCcdhVFf12SETNG" options; do
	case $options in
		p )	export partition="-p $OPTARG"
			echo Print only nodes in partition $OPTARG
			;;
		P )	export all_partitions="--all"
			;;
		u )	# Keep only the 1st username in a comma-separated list
			export username=`echo -n $OPTARG | sed '/,.*$/s///g'`
			# Only a single username is supported, so detect any non-alphanumeric characters
			if [[ "$username" =~ [^a-zA-Z0-9] ]]
			then
				echo "ERROR: Multiple usernames given: $username"
				exit -1
			fi
			if test "`$prefix/sacctmgr -p -n show assoc where users=$username`"
			then
				echo "Select a single Slurm user: $username"
			else
				# An incorrectly configured Slurm database may not contain user associations
				echo "Warning: No Slurm association found in the database for username $username"
			fi
			;;
		g )	export groupname="$OPTARG"
			if test "`getent group $OPTARG`"
			then
				echo Print only users in UNIX group $OPTARG
			else
				echo Error selecting UNIX group $OPTARG
				exit -1
			fi
			;;
		A )	export accountlist=$OPTARG
			if test "`$prefix/sacctmgr -n -p show account $accountlist`"
			then
				echo Select only Slurm account=$accountlist
			else
				echo Error selecting Slurm account $accountlist
				echo Print all available accounts by: sacctmgr show account
				exit -1
			fi
			;;
		a )	export printaccount=1
			echo "Print User(Account) after each JobID"
			;;
		q )	export qoslist=$OPTARG
			if test "`$prefix/sacctmgr -n -p show qos $qoslist`"
			then
				echo Select only QOS=$qoslist
			else
				echo Error selecting QOS $qoslist
				echo Print all available QOSes by: sacctmgr show qos
				exit -1
			fi
			;;
		s|t )	statelist="--states $OPTARG"
			echo Select only nodes with state=$OPTARG
			;;
		R )	export reservationlist="$OPTARG"
			echo Select only nodes with reservation=$OPTARG
			;;
		n|w )	hostlist="-n $OPTARG"
			echo Select only nodes in hostlist=$OPTARG
			;;
		d )	export omitdown=1
			echo Omit nodes with states: $statedown
			;;
		j )	joblist=$OPTARG
			# Check if joblist is running in the Slurm queue and squeue displays job information
			jobfound=`$prefix/squeue -j $joblist -t running -h -O JobID 2>/dev/null`
			if test $? -ne 0 -o -z "$jobfound"
			then
				echo ERROR: Jobs in the list $joblist are not running in the current Slurm queue
				exit 1
			fi
			echo Select only nodes with jobs in joblist=$joblist
			# The "readarray" built-in command was introduced in Bash ver.4
			# See https://www.baeldung.com/linux/join-multiple-lines
			hostlist="-n `$prefix/squeue -j $joblist -t running -h -O NodeList: | (readarray -t ARRAY; IFS=','; echo "${ARRAY[*]}")`"
			;;
		G )	export printgres=1
			echo "GPU GRES (Generic Resource) is printed after each JobID"
			;;
		N )	export printjobname=1
			echo "JobName is printed after each JobID"
			;;
		f|F )	export flaglevel=1
			flag_color="(RED and MAGENTA nodes)"
			if test $options = "F"
			then
				export flaglevel=2	# Flag RED nodes only
				flag_color="(RED nodes)"
			fi
			if test $free_mem_less -ge 0 -o $free_mem_more -ge 0
			then
				echo ERROR: The -f -m -M flags are mutually exclusive
				exit -1
			fi
			export printallnodes=0
			echo Print only nodes that are flagged by \* $flag_color
			;;
		m )	export free_mem_less=$OPTARG
			if test $flaglevel -gt 0 -o $free_mem_more -ge 0
			then
				echo ERROR: The -f -m -M flags are mutually exclusive
				exit -1
			fi
			export printallnodes=0
			echo Select only nodes with free memory LESS than $free_mem_less MB
			;;
		M )	export free_mem_more=$OPTARG
			if test $flaglevel -gt 0 -o $free_mem_less -ge 0
			then
				echo ERROR: The -f -m -M flags are mutually exclusive
				exit -1
			fi
			export printallnodes=0
			echo Select only nodes with free memory GREATER than $free_mem_more MB
			;;
		1 )	export uniquenodes=1
			echo "Only 1 line per node (Unique nodes in multiple partitions are printed once only)"
			;;
		2 )	export uniquenodes=0
			echo "2..N lines per node which participates in multiple partitions"
			;;
		S )	export printjobstarttime=1
			echo "Job StartTime is printed after each JobID/user"
			;;
		E )	export printjobendtime=1
			echo "Job EndTime is printed after each JobID/user"
			;;
		T )	export printtimeused=1
			echo "Job TimeUsed is printed after each JobID/user"
			;;
		C )	export colors=1
			echo Force colors ON in output
			;;
		c )	export colors=0
			echo Force colors OFF in output
			;;
		V ) echo $my_version
			exit 1;;
		h|? ) usage
			exit 1;;
		* ) usage
			exit 1;;
	esac
done

# Test for extraneous command line arguments
if test $# -gt $(($OPTIND-1))
then
	echo ERROR: Too many command line arguments: $*
	usage
	exit 1
fi

# Sanity check of arguments to sinfo
sinfo $all_partitions $partition $hostlist $statelist > /dev/null
# Trap any errors from sinfo
if [[ "$?" -ne 0 ]]
then
	echo "ERROR: sinfo returned with an error message"
	exit -1
fi

# Determine the longest hostname length in the cluster
# The sinfo header NODELIST will set the minimum to 8 chars
# Variable width of the hostname (NODELIST) column 
export hostnamelength=`sinfo -N $all_partitions $partition $hostlist $statelist -O NodeList:30 | tr -d '[:blank:]' | wc --max-line-length`
# Sanity checks of hostnamelength
if [[ $hostnamelength -lt 8 ]]	
then
	export hostnamelength=8
elif [[ $hostnamelength -gt 20 ]]	
then
	echo "Notice: Longest hostname length is $hostnamelength"
	export hostnamelength=20
	echo "Notice: Longest hostname length is truncated to $hostnamelength"
fi

#####################################################################################
#
# Main pestat function: Execute Slurm commands and print output.
#

# Was: $prefix/sinfo -h -N $partition $hostlist $statelist -o "%N %P %C %O %m %e %t %Z %G" | $my_awk '
# $prefix/sinfo -h -N $partition $hostlist $statelist -O "NodeList: ,Partition: ,CPUsState: ,CPUsLoad: ,Memory: ,FreeMem: ,StateCompact: ,Threads: ,Gres: " | $my_awk '
# Column size(width)=30 hopefully suffices to separate columns
$prefix/sinfo -h -N $all_partitions $partition $hostlist $statelist -O "NodeList:30,Partition:30,CPUsState:30,CPUsLoad:30,Memory:30,FreeMem:30,StateCompact:30,Threads:30,Gres:30,GresUsed:30,AllocMem:30" | $my_awk '
# Convert a Slurm memory string (e.g. 32G, 32768M, 0.5T) to megabytes.
function tomb(s,   v, u) {
	if (s == "" || s == "N/A") return 0
	v = s + 0			# leading number
	u = substr(s, length(s), 1)	# unit suffix
	if (u == "T" || u == "t") return v * 1024 * 1024
	if (u == "G" || u == "g") return v * 1024
	if (u == "K" || u == "k") return v / 1024
	return v			# M or no suffix -> megabytes
}

# Number of GPUs in a tres-per-* request string (e.g. gres:gpu:2, gres:gpu); 0 if none.
function gpucount(s,   n) {
	if (s == "" || s == "N/A" || index(s, "gpu") == 0) return 0
	n = s; sub(/[^0-9]*$/, "", n); sub(/.*[^0-9]/, "", n); n = n + 0
	return (n == 0 ? 1 : n)		# a bare "gres:gpu" means 1
}

# GPU type in a gres string (e.g. gpu:Ampere:8 -> Ampere, gres:gpu:Ada -> Ada);
# "" when no type is given (e.g. gres:gpu:1 or a bare gres:gpu).
function gputype(s,   a, n, i, t) {
	n = split(s, a, ":")
	for (i = 1; i < n; i++)
		if (a[i] == "gpu") { t = a[i+1]; return (t ~ /^[0-9]/) ? "" : t }
	return ""
}

BEGIN {
	#####################################################################################
	# Initialization

	# Read the environment variables configuring actions of pestat:
	prefix=ENVIRON["prefix"]
	username=ENVIRON["username"]
	groupname=ENVIRON["groupname"]
	qoslist=ENVIRON["qoslist"]
	accountlist=ENVIRON["accountlist"]
	printaccount=ENVIRON["printaccount"]
	reservationlist=ENVIRON["reservationlist"]
	free_mem_less=ENVIRON["free_mem_less"]
	free_mem_more=ENVIRON["free_mem_more"]
	cpuload_delta1=ENVIRON["cpuload_delta1"]
	cpuload_delta2=ENVIRON["cpuload_delta2"]
	memory_thres1=ENVIRON["memory_thres1"]
	memory_thres2=ENVIRON["memory_thres2"]
	printallnodes=ENVIRON["printallnodes"]
	omitdown=ENVIRON["omitdown"]
	statedown=ENVIRON["statedown"]
	printgres=ENVIRON["printgres"]
	jobgreswidth=0
	maxgpus=ENVIRON["maxgpus"]+0	# Largest GPU count on any node (bar-column width)
	gpubar_minmem=ENVIRON["gpubar_minmem"]+0	# Min MB for a free GPU to count as grabbable
	if (gpubar_minmem <= 0) gpubar_minmem = 1024
	# Per-job GPU fair-share coloring. Green = at/under the true fair share (1.0x) on BOTH
	# CPU and memory. Yellow (borderline) requires CPU fully within fair share AND memory
	# over true fair only up to the nominal/rounded share: RealMemory is below the nominal
	# installed RAM (OS reserve), so users computing nominal/GPU (e.g. 256GB/8 = 32GB) land
	# just over the true fair share (31.2GB) -- that is tolerated. Everything else is red:
	# any CPU over fair, or memory above the nominal fair share.
	gpufair_ok=ENVIRON["gpufair_ok"]+0	# CPU/mem at/under this x true fair -> green
	if (gpufair_ok <= 0) gpufair_ok = 1.0
	gpunom_gran=ENVIRON["gpunom_gran"]+0	# round RealMemory up to this (MB) for nominal RAM
	if (gpunom_gran <= 0) gpunom_gran = 16384
	# Parse per-node "cores:mem:gpus" map for per-job fair-share coloring
	split(ENVIRON["noderatiomap"], nrarr, "|")
	for (nri in nrarr) {
		neq = index(nrarr[nri], "=")
		if (neq > 0) {
			nrnode = substr(nrarr[nri], 1, neq-1)
			if (split(substr(nrarr[nri], neq+1), nrv, ":") == 3 && nrv[3] > 0) {
				noderatiocpu[nrnode] = nrv[1] / nrv[3]
				noderatiomem[nrnode] = nrv[2] / nrv[3]
				# nominal RAM = RealMemory rounded up to gpunom_gran; fair share from that
				nrnom = int((nrv[2] + gpunom_gran - 1) / gpunom_gran) * gpunom_gran
				noderationommem[nrnode] = nrnom / nrv[3]
			}
		}
	}
	# Parse the optional per-node GPU descriptor map: node=descriptor|node=descriptor|...
	# Displayed as a per-node column (next to GRES/used), not per job.
	gpumodelwidth = 15	# minimum width (fits the "arch/model/vram" header)
	split(ENVIRON["gpumodelmap"], gpumodelarr, "|")
	for (gmi in gpumodelarr) {
		gmeq = index(gpumodelarr[gmi], "=")
		if (gmeq > 0) {
			gmval = substr(gpumodelarr[gmi],gmeq+1)
			modelmap[substr(gpumodelarr[gmi],1,gmeq-1)] = gmval
			havemodelmap = 1
			if (length(gmval) > gpumodelwidth) gpumodelwidth = length(gmval)
		}
	}
	printjobname=ENVIRON["printjobname"]
	printjobstarttime=ENVIRON["printjobstarttime"]
	printjobendtime=ENVIRON["printjobendtime"]
	printtimeused=ENVIRON["printtimeused"]
	uniquenodes=ENVIRON["uniquenodes"]
	flaglevel=ENVIRON["flaglevel"]
	hostnamelength=ENVIRON["hostnamelength"]
	jobgracetime=ENVIRON["jobgracetime"]
	colors=ENVIRON["colors"]
	# Define terminal colors for the output if requested
	if (colors != 0) {
		# See http://en.wikipedia.org/wiki/ANSI_escape_code#Colors
		RED="\033[1;31m"
		GREEN="\033[1;32m"
		YELLOW="\033[1;33m"
		BLUE="\033[1;34m"
		MAGENTA="\033[1;35m"
		NORMAL="\033[0m"
	}
	# Omit nodes with states: statedown
	if (omitdown > 0) {
		split(statedown,statedownlist," ")
	}

	if (accountlist != "") selection = selection " -A " accountlist
	if (qoslist != "") selection = selection " -q " qoslist
	if (reservationlist != "") selection = selection " -R " reservationlist
	# The "scontrol show hostnames" command is used to expand NodeList expressions
	HOSTLIST=prefix "/scontrol show hostnames "

	#####################################################################################
	# Gather the list of running jobs with squeue
	# Place JobName last, just in case it is a null string
	# Place NodeList second before last because it may be very long
	# JOBLIST = prefix "/squeue -t RUNNING -h -O State,JobID,UserName,GroupName,Account,StartTime,EndTime,TimeUsed,Partition,NumNodes,tres-alloc,NodeList,Name " selection
	# Column size(width)=30 hopefully suffices to separate columns
	# The -O output fields must be space-separated, so use :(space) "sufix" and enclose -O fields in '' (octal 047)
	# Older Slurm versions before 20.02 do not support the "sufix" after -O and may thus not work correctly
	JOBLIST = prefix "/squeue -t RUNNING -h -O \047State: ,JobID: ,JobArrayID: ,UserName: ,GroupName: ,Account: ,StartTime: ,EndTime: ,TimeUsed: ,Partition: ,NumNodes: ,tres-alloc: ,Gres: ,tres-per-job: ,tres-per-task: ,tres-per-socket: ,NodeList: ,Name:\047 " selection
	while ((JOBLIST | getline) > 0) {
		JobState=$1
		JobID=$2
		JobArrayID=$3
		User=$4
		Group=$5
		Account=$6
		StartTime=$7
		EndTime=$8
		TimeUsed=$9
		Partition=$10
		NumNodes=$11
		TresAlloc=$12
		Gres=$13
		TresPerJob=$14
		TresPerTask=$15
		TresPerSocket=$16
		NodeList=$17
		JobName=$18
		if (JobName=="") JobName="(None)"
		# Select job information to be printed for this job
		if (JobArrayID == JobID) 
			JobInfo = JobID 
		else {
			# Identify array jobs
			arrayjobs++
			JobInfo = JobID 
		}
		if (printaccount == 0) 
			JobInfo = JobInfo " " User " "
		else {
			JobInfo = JobInfo " " User "(" Account ") "
		}
		if (printgres == 1) {
			gpuraw = ""	# raw "gpu[:type][:count]" string (no color)
			jobcpu = 0; jobmem = 0
			# Authoritative source: the accounting tres-alloc list (gres/gpu=...).
			# Also collect this job CPU and memory for the fair-share coloring below.
			split (TresAlloc, treslist, ",")
			for (i in treslist) {
				if (index(treslist[i], "gres/gpu=") > 0 || index(treslist[i], "gres/gpu:") > 0)
					gpuraw = substr(treslist[i],6)			# omit the "gres/" prefix
				else if (index(treslist[i], "cpu=") == 1) jobcpu = substr(treslist[i],5) + 0
				else if (index(treslist[i], "mem=") == 1) jobmem = tomb(substr(treslist[i],5))
			}
			# Fallback when gres/gpu is not an accounting TRES, so tres-alloc omits it
			# (e.g. AccountingStorageTRES without gres/gpu, or accounting disabled):
			# derive the GPU from the GRES request fields. "--gres=gpu:N" populates Gres
			# (tres-per-node), "--gpus=N" populates tres-per-job, and per-task/socket the
			# remaining fields. Checked in priority order.
			if (gpuraw == "") {
				if      (Gres          != "" && Gres          != "N/A" && index(Gres,          "gpu") > 0) gpuraw = substr(Gres,          6)
				else if (TresPerJob    != "" && TresPerJob    != "N/A" && index(TresPerJob,    "gpu") > 0) gpuraw = substr(TresPerJob,    6)
				else if (TresPerTask   != "" && TresPerTask   != "N/A" && index(TresPerTask,   "gpu") > 0) gpuraw = substr(TresPerTask,   6)
				else if (TresPerSocket != "" && TresPerSocket != "N/A" && index(TresPerSocket, "gpu") > 0) gpuraw = substr(TresPerSocket, 6)
			}
			if (gpuraw == "")
				GRES = RED "(null)" NORMAL	# No GPU for this job
			else {
				# Color the GPU request vs the node fair share: green within fair (CPU & mem);
				# yellow only if CPU within fair AND mem within the nominal share; else red.
				jobgpu = gpuraw
				sub(/[^0-9]*$/, "", jobgpu); sub(/.*[^0-9]/, "", jobgpu)	# trailing count, if any
				jobgpu = jobgpu + 0
				if (jobgpu == 0) jobgpu = 1	# a bare "gpu"/"gpu:type" means 1 GPU
				nodejobgpu[NodeList] += jobgpu	# sum reservations per node (vs GresUsed)
				gcol = GREEN
				if (NodeList in noderatiocpu) {
					cpg = jobcpu/jobgpu; mpg = jobmem/jobgpu
					fcpu = noderatiocpu[NodeList]; fmem = noderatiomem[NodeList]; fnom = noderationommem[NodeList]
					cfrac = (fcpu > 0 ? cpg/fcpu : 0)
					mfrac = (fmem > 0 ? mpg/fmem : 0)
					# CPU: must be fully within fair share for green/yellow; any CPU over
					# the fair share -> red (no CPU tolerance band)
					clvl = 0
					if (fcpu > 0 && cfrac > gpufair_ok) clvl = 2
					# Memory: green at/under true fair; yellow up to the nominal (rounded) fair
					# share -- so a nominal-rounded request (e.g. 32GB where fair is 31.2GB) is
					# borderline, not over; red only above the nominal share.
					mlvl = 0
					if (fmem > 0) { if (mpg > fnom) mlvl = 2; else if (mfrac > gpufair_ok) mlvl = 1 }
					sevlvl = (clvl > mlvl ? clvl : mlvl)
					gcol = (sevlvl == 2 ? RED : (sevlvl == 1 ? YELLOW : GREEN))
					# List only genuine oversubscription (red) at the bottom; yellow is tolerated
					if (sevlvl == 2) {
						reason = ""
						if (clvl == 2) reason = reason sprintf("CPU %.2fx ", cfrac)
						if (mlvl == 2) reason = reason sprintf("mem %.2fx ", mfrac)
						oversub[++noversub] = sprintf("  %-12s %-9s %-12s %-22s %sover%s", NodeList, User, JobArrayID, reason, RED, NORMAL)
					}
				}
				GRES = gcol gpuraw NORMAL
			}
			JobInfo = JobInfo GRES " "
			# Job GRES width for formatting the width below:
			if (length(GRES) > jobgreswidth) jobgreswidth = length(GRES)
		}
		if (printjobname == 1) JobInfo = JobInfo JobName " "
		if (printjobstarttime == 1) JobInfo = JobInfo StartTime " "
		if (printjobendtime == 1) JobInfo = JobInfo EndTime " "
		if (printtimeused == 1) JobInfo = JobInfo TimeUsed " "
		# May select a UNIX group name
		if (groupname != "" && Group != groupname) continue
		# Convert job TimeUsed days-hours:minutes:seconds into seconds
		i = split(TimeUsed,hms,":")
		if (i == 1)
			TimeUsedSec = hms[1]			# Seconds 
		else if (i == 2)
			TimeUsedSec = hms[1]*60 + hms[2]	# Minutes:seconds
		else {
			if (split(hms[1],dh,"-") == 1)
				TimeUsedSec = hms[1]*3600 + hms[2]*60 + hms[3]	# No days- field
			else
				TimeUsedSec = dh[1]*86400 + dh[2]*3600 + hms[2]*60 + hms[3]
		}

		# Create the list of nodes for this job, and expand the list for multiple nodes
		if (index(NodeList,"[") == 0 && index(NodeList,",") == 0) {	# Just a single node name
			jobnodes[1] = NodeList
		} else {		# Multiple nodes when the characters , or [ appear in NodeList
			# Put hostname lines into an array jobnodes[]
			cmd = HOSTLIST NodeList
			i=0
			while ((cmd | getline) > 0) jobnodes[++i] = $1
			close (cmd)
		}
		# Populate the jobs arrays with "JobID User" (Multiple jobs may exist on each node, and EndTime may be added).
		# Populate the partitions array from job info.
		for (i in jobnodes) {
			n = jobnodes[i]
			hostname[n] = n
			jobs[n] = jobs[n] sep[n] JobInfo 
			sep[n] = "| "	# Separating the job list with |
			# Record the TimeUsedSec for the most recently started job on this node
			if (mostrecentjob[n] == 0 || TimeUsedSec < mostrecentjob[n])
				mostrecentjob[n] = TimeUsedSec
			# Has partitions on this node been set previously?
			if (partitions[n] == "") {
				# Set the partition name from this running job
				partitions[n] = Partition
			} else if (partitions[n] != Partition) {
				# This node runs jobs from multiple, distinct partitions: Denote this by a "+"
				multipartitions[n] = "+"
			}
			numjobs[n]++
			if (NumNodes > 1) multinodejobs[n]++		# Increment for nodes running multi-node jobs (%D>1)
			# If username has been selected and node "n" runs job belonging to username:
			if (User == username) selecteduser[n] = User
			if (Group == groupname) selectedgroup[n] = Group
		}
		delete jobnodes
	}
	close (JOBLIST)

	# Aggregate the PENDING queue to show GPU demand (only with -G). Count only jobs that
	# request a GPU, bucketed by reason: jobs blocked on Resources/Priority are genuinely
	# waiting for a GPU (the FIFO queue); the rest are self-limited and not competing.
	if (printgres == 1) {
		PENDLIST = prefix "/squeue -t PENDING -h -O \047tres-per-node: ,tres-per-job: ,tres-per-task: ,tres-per-socket: ,Reason:\047 " selection " " ENVIRON["partition"]
		while ((PENDLIST | getline) > 0) {
			pg = gpucount($1); pf = $1
			if (pg == 0) { pg = gpucount($2); pf = $2 }
			if (pg == 0) { pg = gpucount($3); pf = $3 }
			if (pg == 0) { pg = gpucount($4); pf = $4 }
			if (pg == 0) continue		# not a GPU job -> not GPU demand
			prsn = $5
			if (prsn ~ /^(Resources|Priority|ReqNodeNotAvail|Nodes_required)/) {
				pwaitj++; pwaitg += pg
				pt = gputype(pf); pwaitbytype[pt == "" ? "any" : pt] += pg
			}
			else if (prsn ~ /Held/)              pheld++
			else if (prsn ~ /JobArrayTaskLimit/) parray++
			else if (prsn ~ /Dependency/)        pdep++
			else if (prsn ~ /BeginTime/)         pbegin++
			else                                 pother++
		}
		close (PENDLIST)
	}

	# Format the column header:
	# The job information may include EndTime etc.
	if (arrayjobs == 0)
		JobInfo = "JobID"
	else
		JobInfo = "JobID(JobArrayID)"
	if (printaccount == 0)
		JobInfo = JobInfo " User"
	else
		JobInfo = JobInfo " User(Account)"
	if (printgres == 1) JobInfo = JobInfo " GRES/job"
	if (printjobname == 1) JobInfo = JobInfo " JobName"
	if (printjobstarttime == 1) JobInfo = JobInfo " StartTime"
	if (printjobendtime == 1) JobInfo = JobInfo " EndTime"
	if (printtimeused == 1) JobInfo = JobInfo " TimeUsed"
	JobInfo = JobInfo " | ..."
	# Print a header line (variable hostnamelength)
	if (printgres == 1) {	# Print GRES column (if requested)
		# Optional per-node GPU descriptor column, shown only when a PESTAT_GPU_MODEL map is set
		gmhdr1 = (havemodelmap ? sprintf("%-*s ", gpumodelwidth, "GPU") : "")
		gmhdr2 = (havemodelmap ? sprintf("%-*s ", gpumodelwidth, "arch/model/vram") : "")
		barhdr = sprintf("%*s", maxgpus + 3, "")	# blank header over the GPU availability bar
		printf("%-*s %15s %8s %7s %8s %8s %8s  %-6s %s%s%s\n", hostnamelength, "Hostname", "Partition", "Node", "Num_CPU", "CPUload", "Memsize", "Freemem", "GRES/", barhdr, gmhdr1, "Joblist")
		printf("%-*s %15s %8s %7s %8s %8s %8s  %-6s %s%s%s\n", hostnamelength, "", "", "State", "Use/Tot", "(15min)", "(MB)", "(MB)", "used", barhdr, gmhdr2, JobInfo)
	} else {
		printf("%-*s %15s %8s %7s %8s %8s %8s  %s\n", hostnamelength, "Hostname", "Partition", "Node", "Num_CPU", "CPUload", "Memsize", "Freemem", "Joblist")
		printf("%-*s %15s %8s %7s %8s %8s %8s  %s\n", hostnamelength, "", "", "State", "Use/Tot", "(15min)", "(MB)", "(MB)", JobInfo)
	}
}
{
	#####################################################################################
	# Main section: Process lines from sinfo

	node=$1
	# Selection of subset of nodes
	if (selection != "" && jobs[node] == "") next
	if (username != "" && selecteduser[node] == "") next
	if (groupname != "" && selectedgroup[node] == "") next

	# Get partition information from squeue (job centric info) if possible
	if (uniquenodes && node in partitions) {
		# Add the multipartitions "+" character if jobs from more than 1 partition run on the node
		partition = partitions[node] multipartitions[node]
		if (index($2, "*") > 0)	# Add "*" to nodename in default partition
			partition = partition "*"
	} else {
		# Fallback to node centric information from sinfo (also if uniquenodes is set from the option -2)
		partition = $2
	}
	# CPU info: sinfo -o %C gives number of CPUs by state in the format "allocated/idle/other/total"
	split($3, cpulist, "/")
	allocated_cores = cpulist[1]
	total_cores = cpulist[4]
	delete cpulist
	cpuload=$4
	memory=$5
	freemem=$6
	state=$7
	# See "NODE STATE CODES" in the sinfo manual page
	if (state == "idle~" || state == "drain~") next	# Skip nodes that are powered down (idle~,drain~)
	if (state == "maint") next	# Skip nodes that are reserved for maintenance
	gsub("$", "", state)	# Strip "$" for state=maintenance
	gsub("@", "", state)	# Strip "@" for pending reboot nodes
	# Use the threads per CPU core to calculate "permissible" min/max CPU load:
	threadspercore=$8
	# Generic resources (GRES) associated and used with the node
	nodegres=$9
	gresused=$10
	allocmem=$11			# Slurm-allocated memory (MB), for schedulable-memory headroom
	# Decode the number of GPUs available and used
	if (gresused != "(null)") {
		split(nodegres, gu, ":")
		availgpus=gu[3]
		# gresused example: gpu:A100:1(IDX:3)
		split(gresused, gu, ":")
		split(gu[3], ng, "(")	# Ignore (IDX:?) field
		usedgpus=ng[1]
		delete gu
		delete ng
	} else {
		availgpus=0
		usedgpus=0
	}

	# Build the colored per-GPU availability bar (the [....] schema), one mark per GPU:
	#   blue   = in use (reserved by a running job)
	#   purple = marked used by Slurm but reserved by no job (leaked -- not really in use)
	#   green  = free and usable at the node fair CPU/mem-per-GPU ratio
	#   yellow = free but only below the fair ratio (CPU/mem cramped)
	#   red    = free but blocked (CPU/memory exhausted, or node down/drained/reserved)
	# Padded to the widest node so the following columns stay aligned.
	gpubar = ""
	if (printgres == 1) {
		jobgpus = (node in nodejobgpu ? nodejobgpu[node] : 0)	# GPUs actually reserved by jobs
		barvis = 0
		if (availgpus > 0) {
			free_gpus = availgpus - usedgpus
			if (free_gpus < 0) free_gpus = 0
			grn = 0; ylw = 0; rd = 0
			if (state ~ /^(down|drain|drng|resv|maint|boot|error|comp|fail|unk|pow|plnd|na)/) {
				# Node is not accepting jobs: its free GPUs are unavailable (red)
				rd = free_gpus
			} else {
				cpu_per_gpu = total_cores / availgpus
				mem_per_gpu = memory / availgpus
				free_cores = total_cores - allocated_cores
				if (free_cores < 0) free_cores = 0
				free_mem = memory - allocmem
				if (free_mem < 0) free_mem = 0
				# GPUs that can get at least the fair share of CPU and memory (green)
				grn = free_gpus
				if (cpu_per_gpu > 0 && int(free_cores/cpu_per_gpu) < grn) grn = int(free_cores/cpu_per_gpu)
				if (mem_per_gpu > 0 && int(free_mem/mem_per_gpu) < grn) grn = int(free_mem/mem_per_gpu)
				if (grn < 0) grn = 0
				# GPUs that can take at least a minimal job: >=1 core and >=gpubar_minmem MB (grabbable)
				grab = free_gpus
				if (int(free_cores) < grab) grab = int(free_cores)
				if (int(free_mem/gpubar_minmem) < grab) grab = int(free_mem/gpubar_minmem)
				if (grab < grn) grab = grn
				if (grab > free_gpus) grab = free_gpus
				ylw = grab - grn	# free but below fair share
				rd = free_gpus - grab	# free but blocked (no CPU/mem to pair)
			}
			# Split the "used" marks: reserved by a job (blue) vs leaked/unreserved (purple)
			bluen = (jobgpus < usedgpus ? jobgpus : usedgpus)
			leakn = usedgpus - bluen
			gpubar = "["
			for (gbi=0; gbi<bluen; gbi++) gpubar = gpubar BLUE    "■" NORMAL
			for (gbi=0; gbi<leakn; gbi++) gpubar = gpubar MAGENTA "■" NORMAL
			for (gbi=0; gbi<grn; gbi++)   gpubar = gpubar GREEN   "■" NORMAL
			for (gbi=0; gbi<ylw; gbi++)   gpubar = gpubar YELLOW  "■" NORMAL
			for (gbi=0; gbi<rd; gbi++)    gpubar = gpubar RED     "■" NORMAL
			gpubar = gpubar "]"
			barvis = availgpus + 2
		}
		# Flag GRES accounting mismatch: node GresUsed vs summed job GPU reservations.
		# A leak (GresUsed > reserved) strands GPUs; the reverse means usage GresUsed misses.
		gmismatch = (availgpus > 0 && jobgpus != usedgpus)
		if (gmismatch) {
			gmd = usedgpus - jobgpus; gmad = (gmd < 0 ? -gmd : gmd)
			gresmm[++ngresmm] = sprintf("  %-12s GresUsed %d vs %d reserved by jobs  (%d %s)", \
				node, usedgpus, jobgpus, gmad, (gmd > 0 ? "leaked/unreserved" : "missing from GresUsed"))
		}
		# Tally cluster GPU supply for the queue footer (skip down/drained/reserved nodes)
		if (availgpus > 0 && state !~ /^(down|drain|drng|resv|maint|boot|error|comp|fail|unk|pow|plnd|na)/) {
			qtotgpu += availgpus
			qfreegpu += (availgpus - usedgpus)
			if (usedgpus > jobgpus) qleaked += (usedgpus - jobgpus)
			nodetype = gputype(nodegres); if (nodetype == "") nodetype = "any"
			qfreebytype[nodetype] += (availgpus - usedgpus)
		}
		# Pad to the widest node bar (maxgpus + 2 brackets) plus a separator space
		pad = (maxgpus + 2) - barvis + 1
		for (gbi=0; gbi<pad; gbi++) gpubar = gpubar " "
	}

	# Select only subset of nodes with certain values/states
	listnode = printallnodes
	# Omit nodes with statedown states (a $ may be appended to state)
	if (omitdown > 0) {
		for (i in statedownlist) {
			if (index(state, statedownlist[i]) > 0) next
		}
	}

	if (free_mem_less > 0) {
		# Free memory on the node LESS than free_mem_less
		if (freemem < free_mem_less) listnode++
	} else if (free_mem_more > 0) {
		# Free memory on the node GREATER than free_mem_more
		if (freemem > free_mem_more) listnode++
	} else {
		if (state == "drain" || state == "drng" || state == "resv" || state == "down" || state == "down~" || state == "error" || state == "comp" || state == "maint" || state == "boot") {
			# Flag nodes with status down, drain etc.
			stateflag="*"
			statecolor=RED
			listnode++
		} else {
			stateflag=" "
			statecolor=NORMAL
		}
		# Flag unexpected CPU load average on allocated cores
		ideal_load_max = allocated_cores
		if (usedgpus > 0) {
			# For GPU nodes assume that 1 (or more) CPU tasks per GPU is ideal
			ideal_load_min = usedgpus
			# Max CPU load should be the fraction of GPUs used times total number of cores
			ideal_load_max = (total_cores * usedgpus) / availgpus
		} else if (threadspercore == 1)
			# Single thread per core: Ideal load equals number of physical cores.
		       	ideal_load_min = allocated_cores
		else
			# Multiple threads per CPU core: Load of 1..threadspercore per physical core is OK.
			ideal_load_min = allocated_cores / threadspercore
		# Calculate if cpuload is outside ideal load bounds, plus some deltas
		if (cpuload > ideal_load_max + cpuload_delta1 || cpuload < ideal_load_min - cpuload_delta1) {
			loadflag="*"
			loadcolor=RED
			cpucolor=GREEN
			listnode++
		} else if (cpuload > ideal_load_max + cpuload_delta2 || cpuload < ideal_load_min - cpuload_delta2) {
			loadflag="*"
			loadcolor=MAGENTA
			cpucolor=GREEN
			if (flaglevel == 1) listnode++
		} else {
			loadflag=" "
			loadcolor=NORMAL
			cpucolor=NORMAL
		}
		# Check CPU core utilization
		if (numjobs[node] > allocated_cores) {
 			# Flag unexpected number of jobs: Should be at least 1 task per job
			jobflag="*"
			jobcolor=RED
			listnode++
		} else if (state == "mix" && multinodejobs[node] > 0) {
			# Flag multi-node jobs running on nodes in state==mixed (possibly incorrect node utilization)
			jobflag="*"
			jobcolor=MAGENTA
			listnode++
		} else {
			jobflag=" "
			jobcolor=NORMAL
		}

		# Free memory on the node
		if (freemem < memory*memory_thres1) {	# Very high memory usage (RED)
			memflag="*"
			freememcolor=RED
			memcolor=GREEN
			listnode++
		} else if (freemem < memory*memory_thres2) {	# High memory usage (MAGENTA)
			memflag="*"
			freememcolor=MAGENTA
			memcolor=GREEN
			if (flaglevel == 1) listnode++
		} else {
			memflag=" "
			freememcolor=NORMAL
			memcolor=NORMAL
		}
	}

	# Do not flag nodes whose most recently started job was < jobgracetime seconds ago
	# because Slurm reports the 15-minute load average.
	if (mostrecentjob[node] > 0 && mostrecentjob[node] < jobgracetime) {
		# Override the listnode flag which may have been set above
		listnode = printallnodes
	}
		
	if (listnode > 0 && nodewasprinted[node] == 0) {
		if (uniquenodes > 0) nodewasprinted[node]++	# Count this node (node may be in multiple partitions)
		printf("%-*s %15s ", hostnamelength, node, partition)
		printf("%s%7s%1s%s ", statecolor, state, stateflag, NORMAL)
		printf("%s%3d%s %3d ", cpucolor, allocated_cores, NORMAL, total_cores)
		printf("%s%7.2f%1s%s ", loadcolor, cpuload, loadflag, NORMAL)
		printf("%s%8d %s%8d%1s%s ", memcolor, memory, freememcolor, freemem, memflag, NORMAL)
		if (printgres == 1) {
			gmcol = (havemodelmap ? sprintf("%-*s ", gpumodelwidth, (node in modelmap ? modelmap[node] : "-")) : "")
			# Count field "used/total" with a * marker when GresUsed disagrees with jobs,
			# left-justified to a fixed visible width so the bar column stays aligned.
			cnt = sprintf("%d/%d", availgpus, usedgpus)
			cntmark = (gmismatch ? MAGENTA "*" NORMAL : "")
			cntpad = 6 - length(cnt) - (gmismatch ? 1 : 0); if (cntpad < 0) cntpad = 0
			padsp = ""; for (cpk = 0; cpk < cntpad; cpk++) padsp = padsp " "
			printf("%s%s%s %s%s", cnt, cntmark, padsp, gpubar, gmcol)
		}
		printf("%s%s%1s%s", jobcolor, jobs[node], jobflag, NORMAL)
		printf("\n")
	}
}
END {
	# Legend explaining the -G GPU bar colors and what counts as oversubscription
	if (printgres == 1) {
		printf("\n")
		printf("GPU bar:  %s■%s in use   %s■%s leaked (marked used, no job)   %s■%s free, fair share   %s■%s free, below fair   %s■%s free but blocked / down\n", BLUE, NORMAL, MAGENTA, NORMAL, GREEN, NORMAL, YELLOW, NORMAL, RED, NORMAL)
		printf("Job GPU:  CPU- and memory-per-GPU vs the node fair share (total_cpu/total_gpu, total_mem/total_gpu):\n")
		printf("          %sgreen%s within fair share   %syellow%s borderline (CPU within fair AND mem only up to the nominal/rounded share, e.g. 32GB vs 31.2GB)   %sred%s over (CPU over fair, or mem over nominal)\n", GREEN, NORMAL, YELLOW, NORMAL, RED, NORMAL)
		if (noversub > 0) {
			printf("Oversubscribed jobs (the offending CPU/memory-per-GPU vs node fair share):\n")
			for (oi = 1; oi <= noversub; oi++) printf("%s\n", oversub[oi])
		} else
			printf("Oversubscribed jobs: none\n")
		if (ngresmm > 0) {
			printf("GRES mismatch (* in count; Slurm GresUsed vs summed job reservations):\n")
			for (mi = 1; mi <= ngresmm; mi++) printf("%s\n", gresmm[mi])
		}
		# Per-GPU-type breakdown of demand and free supply (union of types, sorted).
		# A demanded type with zero free GPUs is the bottleneck -> shown in red; free
		# counts are green when >0, red when 0. This explains "jobs wait though GPUs
		# are free": the free ones are the wrong type.
		for (t in qfreebytype) alltypes[t] = 1
		for (t in pwaitbytype) alltypes[t] = 1
		ntypes = asorti(alltypes, sortedtypes)
		dem_by = ""; sup_by = ""
		for (ti = 1; ti <= ntypes; ti++) {
			t = sortedtypes[ti]; fc = qfreebytype[t] + 0
			if (pwaitbytype[t] > 0)
				dem_by = dem_by (dem_by == "" ? "" : ", ") (fc == 0 ? RED : NORMAL) t " " pwaitbytype[t] NORMAL
			if (t in qfreebytype)
				sup_by = sup_by (sup_by == "" ? "" : ", ") t " " (fc > 0 ? GREEN : RED) fc NORMAL
		}
		# Queue (GPU demand) and supply summary
		qnot = ""
		if (pheld)  qnot = qnot sprintf("  %d held", pheld)
		if (parray) qnot = qnot sprintf("  %d array-throttled", parray)
		if (pdep)   qnot = qnot sprintf("  %d dependency", pdep)
		if (pbegin) qnot = qnot sprintf("  %d begin-delayed", pbegin)
		if (pother) qnot = qnot sprintf("  %d other", pother)
		printf("Queue:    waiting for a GPU: %s%d jobs / %d GPUs%s%s%s\n", \
			(pwaitg > 0 ? YELLOW : NORMAL), pwaitj+0, pwaitg+0, NORMAL, \
			(dem_by != "" ? "  [" dem_by "]" : ""), \
			(qnot != "" ? "    not competing:" qnot : ""))
		supnote = (qleaked > 0 ? sprintf("  (>=%d more idle but marked used -- GresUsed leak, see above)", qleaked) : "")
		printf("Supply:   %d / %d GPUs free per Slurm%s%s\n", qfreegpu+0, qtotgpu+0, \
			(sup_by != "" ? "  [" sup_by "]" : ""), supnote)
	}
}'
